apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    initcontainers:
      - name: init-logstash-plugins-install
        image: docker.elastic.co/logstash/logstash:7.2.0
        command:
          - /bin/bash
          - "-c"
          - |
            set -e
            ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
        volumeMounts:
          - name: shared-plugins-logstash
            mountPath: /usr/share/logstash/plugins/
      - name: copy-ro-scripts
        image: busybox
        command: ['sh', '-c']
        args: ['cp /scripts/logstash.yml /etc/pre-install/logstash.yml; chown 1000 /etc/pre-install/logstash.yml; echo "" >> etc/pre-sincedb/sincedb ; chown 1000 /etc/pre-sincedb/sincedb ']
        securityContext:
            runAsUser: 0
        volumeMounts:
          - name: scripts
            mountPath: /scripts/logstash.yml
            subPath: logstash.yml
          - name: logstash-yaml
            mountPath: /etc/pre-install
          - name: sincedb-mount
            mountPath: /etc/pre-sincedb
    containers:
      - name: logstash-sidecar
        image: docker.elastic.co/logstash/logstash:7.2.0
        volumeMounts:
          - name: shared-plugins-logstash
            mountPath: /usr/share/logstash/plugins/
          - name: logstash-yaml
            mountPath: /usr/share/logstash/config/
          - name: logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: sincedb-mount
            mountPath: /opt/testgrid/sincedb
            subPath: sincedb
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ELASTICSEARCH_HOST
            value: ${ESEP}
    volumes:
      - name: shared-plugins-logstash
        emptyDir: {}
      - name: scripts
        configMap:
          name: logstash-yaml
      - name: logstash-yaml
        emptyDir: {}
      - name: logstash-conf
        configMap:
          name: logstash-conf
      - name: sincedb-mount
        emptyDir: {}
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: ELASTICSEARCH_HOST
        value: ${ESEP}

