apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-yaml
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    log.level: debug
    path.logs: /opt/testgrid